# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redes_pass
      MYSQL_DATABASE: test_redes
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  javaspring:
    working_dir: /home/spring
    image: openjdk:23-ea-17-jdk-slim
    command: ./mvnw spring-boot:run
    restart: always
    volumes:
      - .:/home/spring
    ports:
      - 80:8080
    
    

